<?php

namespace Database\Seeders;

use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
                ['name' => 'Serum lotion', 'slug' => 'serum-lotion'],
                ['name' => 'Body wash', 'slug' => 'body-wash'],
                ['name' => 'Herbal shampoo', 'slug' => 'herbal-shampoo'],
                ['name' => 'Shampoo', 'slug' => 'shampoo'],
                ['name' => 'Colour Shampoo', 'slug' => 'colour-shampoo'],
                ['name' => 'Hair colour', 'slug' => 'hair-colour'],
                ['name' => 'Hand cream', 'slug' => 'hand-cream'],
                ['name' => 'Relief Cream', 'slug' => 'relief-cream'],
                ['name' => 'Bleach Cream', 'slug' => 'bleach-cream'],
                ['name' => 'Face cream', 'slug' => 'face-cream'],
                ['name' => 'Moisturiser cream', 'slug' => 'moisturiser-cream'],
                ['name' => 'Moisturiser lotion', 'slug' => 'moisturiser-lotion'],
                ['name' => 'Face serum', 'slug' => 'face-serum'],
                ['name' => 'Face wash', 'slug' => 'face-wash'],
                ['name' => 'Sunscreen cream', 'slug' => 'sunscreen-cream'],
                ['name' => 'Repair cream', 'slug' => 'repair-cream'],
                ['name' => 'Kajol', 'slug' => 'kajol'],
                ['name' => 'Hair oil', 'slug' => 'hair-oil'],
                ['name' => 'Face oil', 'slug' => 'face-oil'],
                ['name' => 'Body oil', 'slug' => 'body-oil'],
                ['name' => 'Mascara', 'slug' => 'mascara'],
                ['name' => 'Concelar', 'slug' => 'concelar'],
                ['name' => 'Setting powder', 'slug' => 'setting-powder'],
                ['name' => 'Setting spray', 'slug' => 'setting-spray'],
                ['name' => 'Hair brush', 'slug' => 'hair-brush'],
                ['name' => 'Hair ban', 'slug' => 'hair-ban'],
                ['name' => 'Eye lashes', 'slug' => 'eye-lashes'],
                ['name' => 'Eye lanse', 'slug' => 'eye-lanse'],
                ['name' => 'Baby cream', 'slug' => 'baby-cream'],
                ['name' => 'Baby moisturiser cream', 'slug' => 'baby-moisturiser-cream'],
                ['name' => 'Baby moisturiser lotion Body', 'slug' => 'baby-moisturiser-lotion-body'],
                ['name' => 'Baby gift set', 'slug' => 'baby-gift-set'],
                ['name' => 'Lip tint', 'slug' => 'lip-tint'],
                ['name' => 'Lipistick', 'slug' => 'lipistick'],
                ['name' => 'Liquid Lipstick', 'slug' => 'liquid-lipstick'],
                ['name' => 'Liquid Eyeliner', 'slug' => 'liquid-eyeliner'],
                ['name' => 'Eye brow shop', 'slug' => 'eye-brow-shop'],
                ['name' => 'Facial Razor', 'slug' => 'facial-razor'],
                ['name' => 'Makeup Foundation', 'slug' => 'makeup-foundation'],
                ['name' => 'Makeup brush', 'slug' => 'makeup-brush'],
                ['name' => 'Foundation', 'slug' => 'foundation'],
                ['name' => 'Face mask', 'slug' => 'face-mask'],
                ['name' => 'Body powder', 'slug' => 'body-powder'],
                ['name' => 'Lotion', 'slug' => 'lotion'],
                ['name' => 'Baby powder', 'slug' => 'baby-powder'],
                ['name' => 'Hair mask', 'slug' => 'hair-mask'],
                ['name' => 'Cleansing foam', 'slug' => 'cleansing-foam'],
                ['name' => 'Healing cream', 'slug' => 'healing-cream'],
                ['name' => 'Body spray', 'slug' => 'body-spray'],
                ['name' => 'Body perfume', 'slug' => 'body-perfume'],
                ['name' => 'Cleansing oil', 'slug' => 'cleansing-oil'],
                ['name' => 'Facial wash', 'slug' => 'facial-wash'],
                ['name' => 'Anti dandruff', 'slug' => 'anti-dandruff'],
                ['name' => 'Tea tree oil', 'slug' => 'tea-tree-oil'],
                ['name' => 'Body scrub', 'slug' => 'body-scrub'],
                ['name' => 'Hair remover', 'slug' => 'hair-remover'],
                ['name' => 'Micellar water', 'slug' => 'micellar-water'],
                ['name' => 'Face scrub', 'slug' => 'face-scrub'],
                ['name' => 'Gel cleanser', 'slug' => 'gel-cleanser'],
                ['name' => 'Eye shadow plate', 'slug' => 'eye-shadow-plate'],
                ['name' => 'Eye shadow foundation', 'slug' => 'eye-shadow-foundation'],
                ['name' => 'High lighter', 'slug' => 'high-lighter'],
                ['name' => 'Hair spa', 'slug' => 'hair-spa'],
                ['name' => 'Conditioner', 'slug' => 'conditioner'],
                ['name' => 'Anti hair fall shampoo', 'slug' => 'anti-hair-fall-shampoo'],
                ['name' => 'Nail polish', 'slug' => 'nail-polish'],
                ['name' => 'Rose water', 'slug' => 'rose-water'],
                ['name' => 'Peeling gel', 'slug' => 'peeling-gel'],
                ['name' => 'Lip careo', 'slug' => 'lip-careo'],
                ['name' => 'Makeup box', 'slug' => 'makeup-box'],
                ['name' => 'Toner', 'slug' => 'toner'],
                ['name' => 'Skin cleanser', 'slug' => 'skin-cleanser'],
                ['name' => 'Vaseline jelly', 'slug' => 'vaseline-jelly'],
                ['name' => 'Pocket spray', 'slug' => 'pocket-spray'],
                ['name' => 'Pocket perfume', 'slug' => 'pocket-perfume'],
                ['name' => 'Shave gel', 'slug' => 'shave-gel'],
                ['name' => 'Shave foam', 'slug' => 'shave-foam'],
                ['name' => 'Face powder', 'slug' => 'face-powder'],
                ['name' => 'Oil control powder', 'slug' => 'oil-control-powder'],
                ['name' => 'Gel', 'slug' => 'gel'],
                ['name' => 'Mask rapier', 'slug' => 'mask-rapier'],
                ['name' => 'Lip oil', 'slug' => 'lip-oil'],
                ['name' => 'Body mist', 'slug' => 'body-mist'],
                ['name' => 'Lip balam', 'slug' => 'lip-balam'],
                ['name' => 'Soap', 'slug' => 'soap'],
                ['name' => 'Hair serum', 'slug' => 'hair-serum'],
                ['name' => 'BB cream', 'slug' => 'bb-cream'],
                ['name' => 'Sheet mask', 'slug' => 'sheet-mask'],
                ['name' => 'Hand wash', 'slug' => 'hand-wash'],
                ['name' => 'Air Freshener', 'slug' => 'air-freshener'],
                ['name' => 'Mouth wash', 'slug' => 'mouth-wash'],
                ['name' => 'Hair cream', 'slug' => 'hair-cream'],
                ['name' => 'Cotton buds', 'slug' => 'cotton-buds'],
                ['name' => 'Shampoo+conditioner', 'slug' => 'shampoo-conditioner'],
                ['name' => 'Shower get', 'slug' => 'shower-get'],
                ['name' => 'Hair gel', 'slug' => 'hair-gel'],
                ['name' => 'Brighting Cream', 'slug' => 'brighting-cream'],
                ['name' => 'Night cream', 'slug' => 'night-cream'],
                ['name' => 'Baby oil', 'slug' => 'baby-oil'],
                ['name' => 'Baby shampoo', 'slug' => 'baby-shampoo'],
                ['name' => 'Baby bath', 'slug' => 'baby-bath'],
                ['name' => 'Hand&body lotion', 'slug' => 'hand-and-body-lotion'],
                ['name' => 'Hair trimmer', 'slug' => 'hair-trimmer'],
                ['name' => 'Hair straight', 'slug' => 'hair-straight'],
                ['name' => 'Hair dry', 'slug' => 'hair-dry'],
                ['name' => 'Hair tonic', 'slug' => 'hair-tonic'],
                ['name' => 'Lip therapy', 'slug' => 'lip-therapy'],
                ['name' => 'Foam cleanser', 'slug' => 'foam-cleanser'],
                ['name' => 'Whiting cream', 'slug' => 'whiting-cream'],
                ['name' => 'Nail remover', 'slug' => 'nail-remover'],
                ['name' => 'Tooth Brush', 'slug' => 'tooth-brush'],
                ['name' => 'Tooth paste', 'slug' => 'tooth-paste'],
                ['name' => 'Lotion powder', 'slug' => 'lotion-powder'],
                ['name' => 'Head to wash', 'slug' => 'head-to-wash'],
                ['name' => 'Vaseline', 'slug' => 'vaseline'],
                ['name' => 'Aloe Vera Gel', 'slug' => 'aloe-vera-gel'],
                ['name' => 'Roll on', 'slug' => 'roll-on'],
                ['name' => 'Massage cream', 'slug' => 'massage-cream'],
                ['name' => 'Hair&body wash', 'slug' => 'hair-and-body-wash'],
                ['name' => 'Nose strips', 'slug' => 'nose-strips'],
            ];

        foreach ($categories as $sl => $category) {
            Category::create([
                'name'       => $category['name'],
                'slug'       => $category['slug'],
                'is_active'  => true,
                'sort_order' => $sl + 1,
                'status'     => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
